attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  Region:
    Upper North Island: 0
  Region ID:
    UNI: 0
embedding_paddings: []
embedding_sizes:
  Region: !!python/tuple
  - 1
  - 1
  Region ID: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 0
log_val_interval: null
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    MCVcrvrgdUA=
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    1Zluu2IPUUA=
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- Region ID
- Region
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- Est_Total_consumption_GWh
- Average daily consumption (kWh)
- Est_Total_demand_GWh
- Est_proportion_of_regional_demand
weight_decay: 0.0
x_categoricals:
- Region ID
- Region
x_reals:
- Est_Total_consumption_GWh
- Average daily consumption (kWh)
- Est_Total_demand_GWh
- Est_proportion_of_regional_demand
