attention_head_size: 2
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.001
log_gradient_flow: false
log_interval: 2
log_val_interval: null
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDQAAADI3NjQ4MzQ4OTA5MjhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyNzY0
      ODM0ODkwOTI4cQFhLgEAAAAAAAAAIFauQw==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDQAAADI3NjQ4MzQ4OTM0MjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyNzY0
      ODM0ODkzNDI0cQFhLgEAAAAAAAAAg2uDQg==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
time_varying_reals_encoder:
- time_idx
- Est_ Total demand (GWh)
- Est_ proportion of regional demand
- Est_ proportion of national demand
- Average consumption (kWh)
- Average daily consumption (kWh)
- 5th percentile (kWh)
- 25th percentile (kWh)
- 50th percentile (kWh)
- 75th percentile (kWh)
- 95th percentile (kWh)
- Coverage %
weight_decay: 0.0
x_categoricals: []
x_reals:
- time_idx
- Est_ Total demand (GWh)
- Est_ proportion of regional demand
- Est_ proportion of national demand
- Average consumption (kWh)
- Average daily consumption (kWh)
- 5th percentile (kWh)
- 25th percentile (kWh)
- 50th percentile (kWh)
- 75th percentile (kWh)
- 95th percentile (kWh)
- Coverage %
